### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by corybill** [confluentinc/kafka-rest-node#17]
I see a beta version in your package.json (i.e. pre 1.0.0) and a very small set of tests.  The basic scenario I am setting up while following the instructions in the README is failing.  So, is this node module production ready?

**Comment by gwenshap** [comment]
The Rest Proxy this uses is production ready, maintained and supported. This client was intended as example code to go with this blog: http://www.confluent.io/blog/getting-started-with-kafka-in-node.js-with-the-confluent-rest-proxy

**Comment by ewencp** [comment]
However, we're happy to accept PRs and improvements. The wrapper itself is pretty straightforward, so getting it into production ready state mostly requires more tests/testing.

**Comment by corybill** [comment]
Thanks for the quick responses.  I very well may help out writing some tests.
