### ISSUE TITLE
Producer (with avro) giving error after 1000 messages

### ISSUE THREAD

**Issue by rajeshnambiar** [confluentinc/kafka-rest-node#21]
When using the kafka-rest node module with avro and schema registry, the messages starts giving "500 internal server" error after producing 1000 messages (1000 separate produce requests). Based on my understanding this issue happens when we don't reuse the schema object. The kafka-rest documentation says that this is handled transparently for us. I don't see that happening. Am I missing something?

I don't see this issue when I use schema id with kafka rest proxy api directly.

**Comment by ewencp** [comment]
@rajeshnambiar I think you're seeing an issue that's actually in the REST proxy, which has been fixed by some caching in https://github.com/confluentinc/kafka-rest/pull/222. Can you retry using the latest `master` build of the REST proxy (or after the next release)?

**Comment by rajeshnambiar** [comment]
Thanks @ewencp !. I will try this with the next release of REST proxy
